// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzT9QcYKJZCj2GK3Ux7C-384dRKEPt8OM',
    appId: '1:363851869536:android:793ae5abc7201f510c0205',
    messagingSenderId: '363851869536',
    projectId: 'kfc-food-6ef9b',
    storageBucket: 'kfc-food-6ef9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQtcs6P5Oo5t0sCqwjdp9_f6MaBsGCUs',
    appId: '1:363851869536:ios:7f5691a38b24fe070c0205',
    messagingSenderId: '363851869536',
    projectId: 'kfc-food-6ef9b',
    storageBucket: 'kfc-food-6ef9b.firebasestorage.app',
    androidClientId: '363851869536-nqlui7pc8p7u9h80n9ugpi991iqmq9gg.apps.googleusercontent.com',
    iosClientId: '363851869536-moujsecv86ujfpb9nfurmorv6gbbl433.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdgroDBRekxRp-r2ljANR1jiM_kFBZ1xM',
    appId: '1:363851869536:web:e00bf830037bc1450c0205',
    messagingSenderId: '363851869536',
    projectId: 'kfc-food-6ef9b',
    authDomain: 'kfc-food-6ef9b.firebaseapp.com',
    storageBucket: 'kfc-food-6ef9b.firebasestorage.app',
  );
}
